"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.conf.global_settings import MEDIA_URL, MEDIA_ROOT, STATICFILES_DIRS, EMAIL_BACKEND, EMAIL_HOST, EMAIL_PORT, \
    EMAIL_USE_TLS, EMAIL_HOST_PASSWORD

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5b=3*7h=4l@v2n@b)4orusj@fq)w=g8oku))u75e07b23fno6o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["template"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

NOTCHPAY_API_KEY = 'pk_test.Js1GiyW1VSAJpuxWtcEWGlFPKdKgQuW5IAGrZEf6gtXpUOdnep0jz1U79js4Mr73j0nNYEGjI0zuNxJJBDR9jbpwUTlFAwsggrhFBA3PWvgKkElkGNiYjDxcD0ows'
NOTCHPAY_GRANT_KEY = 'sk_test.PcFBnwnnS43IJpNiblFCM1DVvlBqhK3CieqVp5W3X2vvt0V0pOW0geodiBzsZmergxXlZnCDWIu9FDjFtGYeURub9IMHi47aHupFWVJ5USYz6IsxCiNbnySoOEWKH'
NOTCHPAY_WEBHOOK_SECRET = 'hsk_test.mKKHd3H4u8oW16qki0DvCMFtxieejtkOMjcQVOuTaoFTj2J7Fm99qmqrtpP1I2dQqrYNlDhd90BTOF4EJn8yw3nQ5Y1S6fgH6175P5hPgF74hziej13i0CtTw1a1Q'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
AUTH_USER_MODEL = "accounts.Shopper"
STRIPE_PUBLISHABLE_KEY = "pk_test_51RHkUvP6yG6oXMmR0FyNYEJ49DXdVlv6v7mbylMXmPUwVT3vw6uUMxeXxsCmELZvBI5eatXWvZms7PE0OnlBE9ne00EOtlQedd"
STRIPE_SECRET_KEY = "sk_test_51RHkUvP6yG6oXMmRtu2sCPfm9USTgmeOU40UR2OE4y1yGLGp4M4iXfKXHd5yrZSaSdO4JiVNmlZfgTGQvqrPm8kp00JNto5wxs"

# gestion des mails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'jordankamgang00@gamil.com'
EMAIL_HOST_PASSWORD = 'Moncompte1'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
