# Generated by Django 5.1.7 on 2025-04-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_electronique_thumbnail_order_electronique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_electronique',
            name='Electronique',
        ),
        migrations.AddField(
            model_name='order_electronique',
            name='electronique',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='store.electronique'),
            preserve_default=False,
        ),
    ]
