# Generated by Django 5.1.7 on 2025-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_electronique_electronique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_electronique',
            old_name='electronique',
            new_name='Electronique',
        ),
        migrations.AlterField(
            model_name='electronique',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='electroniques'),
        ),
    ]
