# Generated by Django 5.1.7 on 2025-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_electronique_order_electronique_electronique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronique',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='electronique'),
        ),
    ]
