# Generated by Django 5.1.7 on 2025-05-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_subcriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcriber',
            new_name='Subscriber',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subcribed_on',
            new_name='subscribed_on',
        ),
    ]
