# Generated by Django 5.1.7 on 2025-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_subcriber_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bijoux_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
